### ISSUE TITLE
The Hero's Journey

### ISSUE THREAD

**Issue by DavidDeLaTorre** [Ar-Ess/NoPhysicsLibrary#1]
Greetings, brave hero! Thou art destined to defeat the Demon Lord and bring peace to these lands. 

But before you are worthy of battling the final boss, thou shall complete these side quests:

CODE ARCHITECTURE
 - [x] Re-structure code, clean-up & modularisation.

SCENARIOS
 - [x] Build several scenarios, one per audio effect showcase (TBD)
     - [x] Audio propagation (attenuation due to distance)
     - [x] Audio absorption (due to obstacle)
     - [x] Audio reflection (wall)
     - [x] Phase change (air --> water)
     - [x] "Atmosphere" density change (depressurization lock)
     - [x] "Atmosphere" composition change (oxygen, nitrogen, helium, water, etc.)
     - [x] Player steps on different suraces (metal, wood, etc.)
     - [x] Player movement (dash, fall, collision, etc.) sounds. Apply all above effects.
 - [x] Test & polish scenarios. These will be your showcase during the presentation!
 
PHYSICS
 - [x] Core: motion integrator
 - [x] Core: forces (gravity, aerodynamics, hydrodynamics, kinetic/player-driven)
 - [x] Core: collisions (TBC)
 - [x] Pro: material properties (density, young modulus, impedance, etc.)
 - [x] API: query functions for material properties, player status, etc.

AUDIO
 - [x] CORE: implement MiniAudio lib
 - [x] Core: attenuation due to distance
 - [x] Core: absorption/trasmission/reflection due to material
 - [x] Core: fequency change due to material/phase change (air to water, etc.)
 - [x] API: request PhysAPI for material properties
 

...

**Comment by Ar-Ess** [comment]
Issue closed
